# Generated by Django 5.0 on 2024-01-03 07:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titiksurvei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_survei', models.IntegerField()),
                ('survey_name', models.CharField()),
                ('frame_filename', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mpoint', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
