# Generated by Django 5.0 on 2024-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titiksurvei', '0002_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
