# Generated by Django 5.0 on 2024-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titiksurvei', '0003_alter_survei_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='frame_filename',
            field=models.CharField(),
        ),
    ]
