# Generated by Django 5.0 on 2024-01-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titiksurvei', '0009_alter_survei_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survei',
            name='image',
        ),
    ]
